//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AITLibrary.BookWSIntegration {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BookWSSoap", Namespace="http://tempuri.org/")]
    public partial class BookWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllBooksViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertBookReservedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTotalBookReservedByIsbnOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteBookReservedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllReservedBooksByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllAvailableBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksAvailableByBookNameAndAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBorrowedBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBorrowedBooksWithUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBooksBorrowedViewByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertBorrowBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBorrowedBooksByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnBorrowBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksReservedViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksReservedViewByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksBorrowedWithUserViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksBorrowedWithUserViewByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BookWS() {
            this.Url = global::AITLibrary.Properties.Settings.Default.AITLibrary_BookWS_BookWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllBooksViewCompletedEventHandler GetAllBooksViewCompleted;
        
        /// <remarks/>
        public event BookSearchCompletedEventHandler BookSearchCompleted;
        
        /// <remarks/>
        public event insertBookReservedCompletedEventHandler insertBookReservedCompleted;
        
        /// <remarks/>
        public event GetTotalBookReservedByIsbnCompletedEventHandler GetTotalBookReservedByIsbnCompleted;
        
        /// <remarks/>
        public event DeleteBookReservedCompletedEventHandler DeleteBookReservedCompleted;
        
        /// <remarks/>
        public event GetAllReservedBooksByUserIdCompletedEventHandler GetAllReservedBooksByUserIdCompleted;
        
        /// <remarks/>
        public event GetAllAvailableBooksCompletedEventHandler GetAllAvailableBooksCompleted;
        
        /// <remarks/>
        public event GetAllBooksAvailableByBookNameAndAuthorCompletedEventHandler GetAllBooksAvailableByBookNameAndAuthorCompleted;
        
        /// <remarks/>
        public event GetAllBorrowedBooksCompletedEventHandler GetAllBorrowedBooksCompleted;
        
        /// <remarks/>
        public event GetAllBorrowedBooksWithUserCompletedEventHandler GetAllBorrowedBooksWithUserCompleted;
        
        /// <remarks/>
        public event GetBooksBorrowedViewByNameCompletedEventHandler GetBooksBorrowedViewByNameCompleted;
        
        /// <remarks/>
        public event InsertBorrowBookCompletedEventHandler InsertBorrowBookCompleted;
        
        /// <remarks/>
        public event GetAllBorrowedBooksByUserIdCompletedEventHandler GetAllBorrowedBooksByUserIdCompleted;
        
        /// <remarks/>
        public event ReturnBorrowBookCompletedEventHandler ReturnBorrowBookCompleted;
        
        /// <remarks/>
        public event GetAllBooksReservedViewCompletedEventHandler GetAllBooksReservedViewCompleted;
        
        /// <remarks/>
        public event GetAllBooksReservedViewByUserIdCompletedEventHandler GetAllBooksReservedViewByUserIdCompleted;
        
        /// <remarks/>
        public event GetAllBooksBorrowedWithUserViewCompletedEventHandler GetAllBooksBorrowedWithUserViewCompleted;
        
        /// <remarks/>
        public event GetAllBooksBorrowedWithUserViewByUserIdCompletedEventHandler GetAllBooksBorrowedWithUserViewByUserIdCompleted;
        
        /// <remarks/>
        public event DeleteBookCompletedEventHandler DeleteBookCompleted;
        
        /// <remarks/>
        public event InsertBookCompletedEventHandler InsertBookCompleted;
        
        /// <remarks/>
        public event UpdateBookCompletedEventHandler UpdateBookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBooksView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBooksView() {
            object[] results = this.Invoke("GetAllBooksView", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksViewAsync() {
            this.GetAllBooksViewAsync(null);
        }
        
        /// <remarks/>
        public void GetAllBooksViewAsync(object userState) {
            if ((this.GetAllBooksViewOperationCompleted == null)) {
                this.GetAllBooksViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksViewOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksView", new object[0], this.GetAllBooksViewOperationCompleted, userState);
        }
        
        private void OnGetAllBooksViewOperationCompleted(object arg) {
            if ((this.GetAllBooksViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksViewCompleted(this, new GetAllBooksViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BookSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BookSearch(string bookISBN, string bookName, string author) {
            object[] results = this.Invoke("BookSearch", new object[] {
                        bookISBN,
                        bookName,
                        author});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BookSearchAsync(string bookISBN, string bookName, string author) {
            this.BookSearchAsync(bookISBN, bookName, author, null);
        }
        
        /// <remarks/>
        public void BookSearchAsync(string bookISBN, string bookName, string author, object userState) {
            if ((this.BookSearchOperationCompleted == null)) {
                this.BookSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookSearchOperationCompleted);
            }
            this.InvokeAsync("BookSearch", new object[] {
                        bookISBN,
                        bookName,
                        author}, this.BookSearchOperationCompleted, userState);
        }
        
        private void OnBookSearchOperationCompleted(object arg) {
            if ((this.BookSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookSearchCompleted(this, new BookSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertBookReserved", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertBookReserved(int userId, string isbn, string reservedDate) {
            object[] results = this.Invoke("insertBookReserved", new object[] {
                        userId,
                        isbn,
                        reservedDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertBookReservedAsync(int userId, string isbn, string reservedDate) {
            this.insertBookReservedAsync(userId, isbn, reservedDate, null);
        }
        
        /// <remarks/>
        public void insertBookReservedAsync(int userId, string isbn, string reservedDate, object userState) {
            if ((this.insertBookReservedOperationCompleted == null)) {
                this.insertBookReservedOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertBookReservedOperationCompleted);
            }
            this.InvokeAsync("insertBookReserved", new object[] {
                        userId,
                        isbn,
                        reservedDate}, this.insertBookReservedOperationCompleted, userState);
        }
        
        private void OninsertBookReservedOperationCompleted(object arg) {
            if ((this.insertBookReservedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertBookReservedCompleted(this, new insertBookReservedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTotalBookReservedByIsbn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTotalBookReservedByIsbn(string isbn) {
            object[] results = this.Invoke("GetTotalBookReservedByIsbn", new object[] {
                        isbn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetTotalBookReservedByIsbnAsync(string isbn) {
            this.GetTotalBookReservedByIsbnAsync(isbn, null);
        }
        
        /// <remarks/>
        public void GetTotalBookReservedByIsbnAsync(string isbn, object userState) {
            if ((this.GetTotalBookReservedByIsbnOperationCompleted == null)) {
                this.GetTotalBookReservedByIsbnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTotalBookReservedByIsbnOperationCompleted);
            }
            this.InvokeAsync("GetTotalBookReservedByIsbn", new object[] {
                        isbn}, this.GetTotalBookReservedByIsbnOperationCompleted, userState);
        }
        
        private void OnGetTotalBookReservedByIsbnOperationCompleted(object arg) {
            if ((this.GetTotalBookReservedByIsbnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTotalBookReservedByIsbnCompleted(this, new GetTotalBookReservedByIsbnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteBookReserved", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteBookReserved(int reservedId) {
            object[] results = this.Invoke("DeleteBookReserved", new object[] {
                        reservedId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteBookReservedAsync(int reservedId) {
            this.DeleteBookReservedAsync(reservedId, null);
        }
        
        /// <remarks/>
        public void DeleteBookReservedAsync(int reservedId, object userState) {
            if ((this.DeleteBookReservedOperationCompleted == null)) {
                this.DeleteBookReservedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteBookReservedOperationCompleted);
            }
            this.InvokeAsync("DeleteBookReserved", new object[] {
                        reservedId}, this.DeleteBookReservedOperationCompleted, userState);
        }
        
        private void OnDeleteBookReservedOperationCompleted(object arg) {
            if ((this.DeleteBookReservedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteBookReservedCompleted(this, new DeleteBookReservedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllReservedBooksByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllReservedBooksByUserId(int userId) {
            object[] results = this.Invoke("GetAllReservedBooksByUserId", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllReservedBooksByUserIdAsync(int userId) {
            this.GetAllReservedBooksByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetAllReservedBooksByUserIdAsync(int userId, object userState) {
            if ((this.GetAllReservedBooksByUserIdOperationCompleted == null)) {
                this.GetAllReservedBooksByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllReservedBooksByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetAllReservedBooksByUserId", new object[] {
                        userId}, this.GetAllReservedBooksByUserIdOperationCompleted, userState);
        }
        
        private void OnGetAllReservedBooksByUserIdOperationCompleted(object arg) {
            if ((this.GetAllReservedBooksByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllReservedBooksByUserIdCompleted(this, new GetAllReservedBooksByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllAvailableBooks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllAvailableBooks() {
            object[] results = this.Invoke("GetAllAvailableBooks", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAvailableBooksAsync() {
            this.GetAllAvailableBooksAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAvailableBooksAsync(object userState) {
            if ((this.GetAllAvailableBooksOperationCompleted == null)) {
                this.GetAllAvailableBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllAvailableBooksOperationCompleted);
            }
            this.InvokeAsync("GetAllAvailableBooks", new object[0], this.GetAllAvailableBooksOperationCompleted, userState);
        }
        
        private void OnGetAllAvailableBooksOperationCompleted(object arg) {
            if ((this.GetAllAvailableBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllAvailableBooksCompleted(this, new GetAllAvailableBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBooksAvailableByBookNameAndAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBooksAvailableByBookNameAndAuthor(string bookName, string author) {
            object[] results = this.Invoke("GetAllBooksAvailableByBookNameAndAuthor", new object[] {
                        bookName,
                        author});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksAvailableByBookNameAndAuthorAsync(string bookName, string author) {
            this.GetAllBooksAvailableByBookNameAndAuthorAsync(bookName, author, null);
        }
        
        /// <remarks/>
        public void GetAllBooksAvailableByBookNameAndAuthorAsync(string bookName, string author, object userState) {
            if ((this.GetAllBooksAvailableByBookNameAndAuthorOperationCompleted == null)) {
                this.GetAllBooksAvailableByBookNameAndAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksAvailableByBookNameAndAuthorOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksAvailableByBookNameAndAuthor", new object[] {
                        bookName,
                        author}, this.GetAllBooksAvailableByBookNameAndAuthorOperationCompleted, userState);
        }
        
        private void OnGetAllBooksAvailableByBookNameAndAuthorOperationCompleted(object arg) {
            if ((this.GetAllBooksAvailableByBookNameAndAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksAvailableByBookNameAndAuthorCompleted(this, new GetAllBooksAvailableByBookNameAndAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBorrowedBooks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBorrowedBooks() {
            object[] results = this.Invoke("GetAllBorrowedBooks", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBorrowedBooksAsync() {
            this.GetAllBorrowedBooksAsync(null);
        }
        
        /// <remarks/>
        public void GetAllBorrowedBooksAsync(object userState) {
            if ((this.GetAllBorrowedBooksOperationCompleted == null)) {
                this.GetAllBorrowedBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBorrowedBooksOperationCompleted);
            }
            this.InvokeAsync("GetAllBorrowedBooks", new object[0], this.GetAllBorrowedBooksOperationCompleted, userState);
        }
        
        private void OnGetAllBorrowedBooksOperationCompleted(object arg) {
            if ((this.GetAllBorrowedBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBorrowedBooksCompleted(this, new GetAllBorrowedBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBorrowedBooksWithUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBorrowedBooksWithUser() {
            object[] results = this.Invoke("GetAllBorrowedBooksWithUser", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBorrowedBooksWithUserAsync() {
            this.GetAllBorrowedBooksWithUserAsync(null);
        }
        
        /// <remarks/>
        public void GetAllBorrowedBooksWithUserAsync(object userState) {
            if ((this.GetAllBorrowedBooksWithUserOperationCompleted == null)) {
                this.GetAllBorrowedBooksWithUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBorrowedBooksWithUserOperationCompleted);
            }
            this.InvokeAsync("GetAllBorrowedBooksWithUser", new object[0], this.GetAllBorrowedBooksWithUserOperationCompleted, userState);
        }
        
        private void OnGetAllBorrowedBooksWithUserOperationCompleted(object arg) {
            if ((this.GetAllBorrowedBooksWithUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBorrowedBooksWithUserCompleted(this, new GetAllBorrowedBooksWithUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBooksBorrowedViewByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetBooksBorrowedViewByName(string bookName) {
            object[] results = this.Invoke("GetBooksBorrowedViewByName", new object[] {
                        bookName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetBooksBorrowedViewByNameAsync(string bookName) {
            this.GetBooksBorrowedViewByNameAsync(bookName, null);
        }
        
        /// <remarks/>
        public void GetBooksBorrowedViewByNameAsync(string bookName, object userState) {
            if ((this.GetBooksBorrowedViewByNameOperationCompleted == null)) {
                this.GetBooksBorrowedViewByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBooksBorrowedViewByNameOperationCompleted);
            }
            this.InvokeAsync("GetBooksBorrowedViewByName", new object[] {
                        bookName}, this.GetBooksBorrowedViewByNameOperationCompleted, userState);
        }
        
        private void OnGetBooksBorrowedViewByNameOperationCompleted(object arg) {
            if ((this.GetBooksBorrowedViewByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBooksBorrowedViewByNameCompleted(this, new GetBooksBorrowedViewByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertBorrowBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertBorrowBook(int userId, string isbn) {
            object[] results = this.Invoke("InsertBorrowBook", new object[] {
                        userId,
                        isbn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertBorrowBookAsync(int userId, string isbn) {
            this.InsertBorrowBookAsync(userId, isbn, null);
        }
        
        /// <remarks/>
        public void InsertBorrowBookAsync(int userId, string isbn, object userState) {
            if ((this.InsertBorrowBookOperationCompleted == null)) {
                this.InsertBorrowBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertBorrowBookOperationCompleted);
            }
            this.InvokeAsync("InsertBorrowBook", new object[] {
                        userId,
                        isbn}, this.InsertBorrowBookOperationCompleted, userState);
        }
        
        private void OnInsertBorrowBookOperationCompleted(object arg) {
            if ((this.InsertBorrowBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertBorrowBookCompleted(this, new InsertBorrowBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBorrowedBooksByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBorrowedBooksByUserId(int userId) {
            object[] results = this.Invoke("GetAllBorrowedBooksByUserId", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBorrowedBooksByUserIdAsync(int userId) {
            this.GetAllBorrowedBooksByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetAllBorrowedBooksByUserIdAsync(int userId, object userState) {
            if ((this.GetAllBorrowedBooksByUserIdOperationCompleted == null)) {
                this.GetAllBorrowedBooksByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBorrowedBooksByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetAllBorrowedBooksByUserId", new object[] {
                        userId}, this.GetAllBorrowedBooksByUserIdOperationCompleted, userState);
        }
        
        private void OnGetAllBorrowedBooksByUserIdOperationCompleted(object arg) {
            if ((this.GetAllBorrowedBooksByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBorrowedBooksByUserIdCompleted(this, new GetAllBorrowedBooksByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnBorrowBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReturnBorrowBook(int bid, string returnDate) {
            object[] results = this.Invoke("ReturnBorrowBook", new object[] {
                        bid,
                        returnDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnBorrowBookAsync(int bid, string returnDate) {
            this.ReturnBorrowBookAsync(bid, returnDate, null);
        }
        
        /// <remarks/>
        public void ReturnBorrowBookAsync(int bid, string returnDate, object userState) {
            if ((this.ReturnBorrowBookOperationCompleted == null)) {
                this.ReturnBorrowBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnBorrowBookOperationCompleted);
            }
            this.InvokeAsync("ReturnBorrowBook", new object[] {
                        bid,
                        returnDate}, this.ReturnBorrowBookOperationCompleted, userState);
        }
        
        private void OnReturnBorrowBookOperationCompleted(object arg) {
            if ((this.ReturnBorrowBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnBorrowBookCompleted(this, new ReturnBorrowBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBooksReservedView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBooksReservedView() {
            object[] results = this.Invoke("GetAllBooksReservedView", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksReservedViewAsync() {
            this.GetAllBooksReservedViewAsync(null);
        }
        
        /// <remarks/>
        public void GetAllBooksReservedViewAsync(object userState) {
            if ((this.GetAllBooksReservedViewOperationCompleted == null)) {
                this.GetAllBooksReservedViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksReservedViewOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksReservedView", new object[0], this.GetAllBooksReservedViewOperationCompleted, userState);
        }
        
        private void OnGetAllBooksReservedViewOperationCompleted(object arg) {
            if ((this.GetAllBooksReservedViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksReservedViewCompleted(this, new GetAllBooksReservedViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBooksReservedViewByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBooksReservedViewByUserId(int userId) {
            object[] results = this.Invoke("GetAllBooksReservedViewByUserId", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksReservedViewByUserIdAsync(int userId) {
            this.GetAllBooksReservedViewByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetAllBooksReservedViewByUserIdAsync(int userId, object userState) {
            if ((this.GetAllBooksReservedViewByUserIdOperationCompleted == null)) {
                this.GetAllBooksReservedViewByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksReservedViewByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksReservedViewByUserId", new object[] {
                        userId}, this.GetAllBooksReservedViewByUserIdOperationCompleted, userState);
        }
        
        private void OnGetAllBooksReservedViewByUserIdOperationCompleted(object arg) {
            if ((this.GetAllBooksReservedViewByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksReservedViewByUserIdCompleted(this, new GetAllBooksReservedViewByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBooksBorrowedWithUserView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBooksBorrowedWithUserView() {
            object[] results = this.Invoke("GetAllBooksBorrowedWithUserView", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksBorrowedWithUserViewAsync() {
            this.GetAllBooksBorrowedWithUserViewAsync(null);
        }
        
        /// <remarks/>
        public void GetAllBooksBorrowedWithUserViewAsync(object userState) {
            if ((this.GetAllBooksBorrowedWithUserViewOperationCompleted == null)) {
                this.GetAllBooksBorrowedWithUserViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksBorrowedWithUserViewOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksBorrowedWithUserView", new object[0], this.GetAllBooksBorrowedWithUserViewOperationCompleted, userState);
        }
        
        private void OnGetAllBooksBorrowedWithUserViewOperationCompleted(object arg) {
            if ((this.GetAllBooksBorrowedWithUserViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksBorrowedWithUserViewCompleted(this, new GetAllBooksBorrowedWithUserViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllBooksBorrowedWithUserViewByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllBooksBorrowedWithUserViewByUserId(int userId) {
            object[] results = this.Invoke("GetAllBooksBorrowedWithUserViewByUserId", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksBorrowedWithUserViewByUserIdAsync(int userId) {
            this.GetAllBooksBorrowedWithUserViewByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetAllBooksBorrowedWithUserViewByUserIdAsync(int userId, object userState) {
            if ((this.GetAllBooksBorrowedWithUserViewByUserIdOperationCompleted == null)) {
                this.GetAllBooksBorrowedWithUserViewByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksBorrowedWithUserViewByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksBorrowedWithUserViewByUserId", new object[] {
                        userId}, this.GetAllBooksBorrowedWithUserViewByUserIdOperationCompleted, userState);
        }
        
        private void OnGetAllBooksBorrowedWithUserViewByUserIdOperationCompleted(object arg) {
            if ((this.GetAllBooksBorrowedWithUserViewByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksBorrowedWithUserViewByUserIdCompleted(this, new GetAllBooksBorrowedWithUserViewByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteBook(string isbn) {
            object[] results = this.Invoke("DeleteBook", new object[] {
                        isbn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteBookAsync(string isbn) {
            this.DeleteBookAsync(isbn, null);
        }
        
        /// <remarks/>
        public void DeleteBookAsync(string isbn, object userState) {
            if ((this.DeleteBookOperationCompleted == null)) {
                this.DeleteBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteBookOperationCompleted);
            }
            this.InvokeAsync("DeleteBook", new object[] {
                        isbn}, this.DeleteBookOperationCompleted, userState);
        }
        
        private void OnDeleteBookOperationCompleted(object arg) {
            if ((this.DeleteBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteBookCompleted(this, new DeleteBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertBook(string isbn, string bookName, int author, int category, int language, int publishYear, int pages, string publisher) {
            object[] results = this.Invoke("InsertBook", new object[] {
                        isbn,
                        bookName,
                        author,
                        category,
                        language,
                        publishYear,
                        pages,
                        publisher});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertBookAsync(string isbn, string bookName, int author, int category, int language, int publishYear, int pages, string publisher) {
            this.InsertBookAsync(isbn, bookName, author, category, language, publishYear, pages, publisher, null);
        }
        
        /// <remarks/>
        public void InsertBookAsync(string isbn, string bookName, int author, int category, int language, int publishYear, int pages, string publisher, object userState) {
            if ((this.InsertBookOperationCompleted == null)) {
                this.InsertBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertBookOperationCompleted);
            }
            this.InvokeAsync("InsertBook", new object[] {
                        isbn,
                        bookName,
                        author,
                        category,
                        language,
                        publishYear,
                        pages,
                        publisher}, this.InsertBookOperationCompleted, userState);
        }
        
        private void OnInsertBookOperationCompleted(object arg) {
            if ((this.InsertBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertBookCompleted(this, new InsertBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateBook(string updatedIsbn, string bookName, int author, int category, int language, int publishYear, int pages, string publisher, string isbn) {
            object[] results = this.Invoke("UpdateBook", new object[] {
                        updatedIsbn,
                        bookName,
                        author,
                        category,
                        language,
                        publishYear,
                        pages,
                        publisher,
                        isbn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBookAsync(string updatedIsbn, string bookName, int author, int category, int language, int publishYear, int pages, string publisher, string isbn) {
            this.UpdateBookAsync(updatedIsbn, bookName, author, category, language, publishYear, pages, publisher, isbn, null);
        }
        
        /// <remarks/>
        public void UpdateBookAsync(string updatedIsbn, string bookName, int author, int category, int language, int publishYear, int pages, string publisher, string isbn, object userState) {
            if ((this.UpdateBookOperationCompleted == null)) {
                this.UpdateBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBookOperationCompleted);
            }
            this.InvokeAsync("UpdateBook", new object[] {
                        updatedIsbn,
                        bookName,
                        author,
                        category,
                        language,
                        publishYear,
                        pages,
                        publisher,
                        isbn}, this.UpdateBookOperationCompleted, userState);
        }
        
        private void OnUpdateBookOperationCompleted(object arg) {
            if ((this.UpdateBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBookCompleted(this, new UpdateBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBooksViewCompletedEventHandler(object sender, GetAllBooksViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BookSearchCompletedEventHandler(object sender, BookSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void insertBookReservedCompletedEventHandler(object sender, insertBookReservedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertBookReservedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertBookReservedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetTotalBookReservedByIsbnCompletedEventHandler(object sender, GetTotalBookReservedByIsbnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTotalBookReservedByIsbnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTotalBookReservedByIsbnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteBookReservedCompletedEventHandler(object sender, DeleteBookReservedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteBookReservedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteBookReservedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllReservedBooksByUserIdCompletedEventHandler(object sender, GetAllReservedBooksByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllReservedBooksByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllReservedBooksByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllAvailableBooksCompletedEventHandler(object sender, GetAllAvailableBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllAvailableBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllAvailableBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBooksAvailableByBookNameAndAuthorCompletedEventHandler(object sender, GetAllBooksAvailableByBookNameAndAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksAvailableByBookNameAndAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksAvailableByBookNameAndAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBorrowedBooksCompletedEventHandler(object sender, GetAllBorrowedBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBorrowedBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBorrowedBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBorrowedBooksWithUserCompletedEventHandler(object sender, GetAllBorrowedBooksWithUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBorrowedBooksWithUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBorrowedBooksWithUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetBooksBorrowedViewByNameCompletedEventHandler(object sender, GetBooksBorrowedViewByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBooksBorrowedViewByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBooksBorrowedViewByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertBorrowBookCompletedEventHandler(object sender, InsertBorrowBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertBorrowBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertBorrowBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBorrowedBooksByUserIdCompletedEventHandler(object sender, GetAllBorrowedBooksByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBorrowedBooksByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBorrowedBooksByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReturnBorrowBookCompletedEventHandler(object sender, ReturnBorrowBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnBorrowBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnBorrowBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBooksReservedViewCompletedEventHandler(object sender, GetAllBooksReservedViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksReservedViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksReservedViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBooksReservedViewByUserIdCompletedEventHandler(object sender, GetAllBooksReservedViewByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksReservedViewByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksReservedViewByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBooksBorrowedWithUserViewCompletedEventHandler(object sender, GetAllBooksBorrowedWithUserViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksBorrowedWithUserViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksBorrowedWithUserViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAllBooksBorrowedWithUserViewByUserIdCompletedEventHandler(object sender, GetAllBooksBorrowedWithUserViewByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksBorrowedWithUserViewByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksBorrowedWithUserViewByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteBookCompletedEventHandler(object sender, DeleteBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertBookCompletedEventHandler(object sender, InsertBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateBookCompletedEventHandler(object sender, UpdateBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591